const REPORT_PAGE_STYLES = [
  ':root{--panel:#ffffff;--line:#d7ddd4;--text:#1d3430;--muted:#5a6f69;--accent:#0f7b62;}',
  'body{margin:0;background:linear-gradient(180deg,#e8f3ef,#f6f7f3);font-family:"Segoe UI",Arial,sans-serif;color:var(--text);padding:16px;}',
  '.header{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px;}',
  '.title{font-size:30px;font-weight:700;margin:0;}',
  '.toolbar-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;}',
  '.range-picker{display:flex;align-items:center;gap:8px;font-size:13px;color:var(--muted);}',
  '.range-picker select{border:1px solid var(--line);background:#fff;border-radius:8px;padding:8px 10px;color:var(--text);font:inherit;}',
  '.muted{color:var(--muted);font-size:12px;}',
  '.btn{border:0;background:var(--accent);color:#fff;padding:10px 14px;border-radius:8px;cursor:pointer;font-weight:600;}',
  '.btn-secondary{background:#345f56;}',
  '.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;margin-bottom:14px;}',
  '.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:10px;}',
  '.card h4{margin:0 0 6px 0;color:var(--muted);font-size:12px;}',
  '.card p{margin:0;font-size:20px;font-weight:700;}',
  '.note{margin:0 0 12px 0;}',
  '.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px;margin-bottom:12px;}',
  '.panel-header{display:flex;justify-content:space-between;align-items:flex-start;gap:10px;margin-bottom:12px;}',
  'h3{margin:0 0 8px 0;font-size:20px;}',
  'table{width:100%;border-collapse:collapse;}',
  'th,td{border:1px solid var(--line);padding:8px;text-align:left;font-size:13px;}',
  'th{background:#eef3f2;}',
  '.hidden{display:none;}',
  '.export-panel{background:linear-gradient(180deg,#fbfdfc,#f4f8f6);}',
  '.export-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;margin-bottom:10px;}',
  '.export-grid label{display:flex;flex-direction:column;gap:6px;font-size:13px;color:var(--muted);}',
  '.export-grid label.hidden{display:none;}',
  '.export-grid .project-branch-matrix{grid-column:1 / -1;background:#fff;border:1px solid var(--line);border-radius:10px;padding:10px;}',
  '.export-grid .project-branch-matrix.hidden{display:none;}',
  '.project-branch-matrix h4{margin:0 0 8px 0;font-size:14px;color:var(--text);}',
  '.project-branch-matrix-head,.project-branch-row{display:grid;grid-template-columns:minmax(280px,1fr) 2fr;gap:12px;align-items:start;}',
  '.project-branch-matrix-head{font-size:12px;color:var(--muted);padding:0 2px 6px 2px;}',
  '.project-branch-matrix-body{display:grid;gap:8px;}',
  '.project-branch-row{border:1px solid var(--line);border-radius:8px;padding:10px;background:#fafcfb;}',
  '.project-branch-repo{display:flex;align-items:flex-start;gap:8px;}',
  '.project-branch-repo-label{font-size:12px;line-height:1.4;word-break:break-all;color:var(--text);}',
  '.project-branch-branches{display:flex;flex-wrap:wrap;gap:8px 12px;}',
  '.project-branch-branch{display:inline-flex;align-items:center;gap:6px;font-size:12px;color:var(--text);}',
  '.project-branch-branch input{margin:0;}',
  '.export-grid select,.export-grid input{border:1px solid var(--line);background:#fff;border-radius:8px;padding:8px 10px;color:var(--text);font:inherit;}',
  '.export-grid select:disabled,.export-grid input:disabled{background:#edf3f1;color:#89a099;}',
  '.export-error{min-height:16px;margin-bottom:8px;}',
  '.heatline-labels{display:flex;justify-content:space-between;gap:10px;font-size:12px;color:var(--muted);margin-bottom:10px;}',
  '.heatline-track{border-radius:999px;border:1px solid rgba(15,123,98,0.12);box-shadow:inset 0 0 0 1px rgba(255,255,255,0.25);padding:4px;background:#f4f8f6;overflow:hidden;}',
  '.heatline-grid{display:grid;gap:1px;}',
  '.heatline-cell{display:block;height:20px;min-width:0;}',
  '@media (max-width:900px){.project-branch-matrix-head,.project-branch-row{grid-template-columns:1fr;}}',
  '@media (max-width:720px){.header{align-items:flex-start;flex-direction:column;}}'
].join('');

module.exports = {
  REPORT_PAGE_STYLES
};
